name: rebuild-cache
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  rebuild-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: 'experimental-features = nix-command flakes'
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: nixhelm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check for updates
        run: nix run .#helmupdater -- update-all --commit --rebuild
      - name: Push updates
        run: git push
